- debug: msg="Starting sync_gateway with config {{ sync_gateway_config_filepath }}"

- name: SYNC GATEWAY | Start sync_gateway service on Windows
  win_service:
    name: SyncGateway
    state: started

# There is no win_wait_for
# This workaround delegates port check to localhost
- name: SYNC GATEWAY | Wait until sync gateway to listen on port
  wait_for:
    host={{ ansible_host }}
    port=4984
    timeout=300
  delegate_to: localhost
